language: python

services:
  - xvfb

python:
  - "3.7.3"

install: 
 - pip install -r requirements.txt
 # This is for running the tests
 - pip install pytest pytest-cov codecov

script: 
  # run tests
  - pytest --cov=src
  - codecov

  # TODO: test pip pip installation
