# doesn't work (yet?) on windows, so skip it

language: python            # this works for Linux but is an error on macOS or Windows
matrix:
  include:
    - name: "Python 3.7.1 on Xenial Linux"
      python: 3.7           # this works for Linux but is ignored on macOS or Windows
      dist: xenial          # required for Python >= 3.7
    - name: "Python 3.7.2 on macOS"
      os: osx
      osx_image: xcode10.2  # Python 3.7.2 running on macOS 10.14.3
      language: shell       # 'language: python' is an error on Travis CI macOS
    # - name: "Python 3.7.3 on Windows"
    #   os: windows           # Windows 10.0.17134 N/A Build 17134
    #   language: shell       # 'language: python' is an error on Travis CI Windows
    #   before_install: choco install python
    #   env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
install:
  - pip3 install --upgrade pip  # all three OSes agree about 'pip3'
  - pip install -r requirements.txt
  - export PYTHONPATH=$PYTHONPATH:$(pwd) # see https://stackoverflow.com/questions/25756134/how-to-add-my-module-to-travis-ci-pythonpath
  # - python3 setup.py install
# 'python' points to Python 2.7 on macOS but points to Python 3.7 on Linux and Windows
# 'python3' is a 'command not found' error on Windows but 'py' works on Windows only
script: python3 -m tests/test_testing.py #|| python -m tests/test_testing.py
